services:
  tts-bot:
    build: .
    container_name: pi-tts-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./logs:/app/logs
      - tts_cache:/app/.cache
    networks:
      - bot_network

volumes:
  tts_cache:

networks:
  bot_network:
    driver: bridge
